services:
  mongodb:
    image: 'mongo'
    env_file:
      - ./.env
  selenium:
    image: 'selenium/standalone-chrome'
  backend:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    depends_on:
      - mongodb
      - selenium
