services:
  mongodb:
    image: 'mongo'
    env_file:
      - ./.env
  backend:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    depends_on:
      - mongodb
